### ISSUE TITLE
Minimum 1 nugget

### ISSUE THREAD

**Issue by Xanatos00** [mega-gigaMynetest/rythium#12]
Serait-il possible d'enlever le 0 sur l'aléatoire de pop d'un nugget ?
Avoir au minimum 1 nugget par arbre.

**Comment by mega-gigaMynetest** [comment]
En réalité, la fonction qui fait pousser l'arbre ne passe fonctionne pas réellement comme ça. Pour chaque feuille il y a une chance sur 25 pour l'intérieur et 1 chance sur 50 pour l'extérieur que ce soit pas une feuille mais un nugget, ce qui veut dire qu'il y a pas d'ensemble définit de limite du nugget. Avec une chance extrème, on pourrait avoir 15 nugget dans un seul arbre.
Cependant, j'ai quand même une idée pour contourner cela, je vais tester
