### ISSUE TITLE
Tronc spécifique

### ISSUE THREAD

**Issue by Xanatos00** [mega-gigaMynetest/rythium#13]
On pourrait avoir un tronc d'arbre spécifique au rythium dérivé de la la couleur des feuilles.

**Comment by mega-gigaMynetest** [comment]
En fait je ne l'ai pas fait car je trouve que appart un peu d'esthétique ça rajoute vraiment rien de faire un nouveau tronc, et il en existe déjà vraiment beaucoup sur le jeu + les mods comme moretrees, etheral ect
Si d'autres gens pensent que c'est plus sympa un tronc spécifique je le ferai
