### ISSUE TITLE
Tournevis rythium

### ISSUE THREAD

**Issue by Xanatos00** [mega-gigaMynetest/rythium#14]
Idée d'objet basé sur le rythium: un tournevis quasi-indestructible ?

**Comment by mega-gigaMynetest** [comment]
Absolument très peu d'intérêt si c'est juste un tournevis qui se casse pas, vu le prix du rythium, par contre si il a d'autres particularités pourquoi pas.
Par exemple pouvoir sélectionner un certains nombres de nodes et les tourner tous en même temps de la même façon ?
