### ISSUE TITLE
Organisation du code

### ISSUE THREAD

**Issue by Grossam** [mega-gigaMynetest/rythium#3]
Comme tu as vu, j'avais prévu de répartir le code sur plusieurs fichiers en mettant tout les nodes dans nodes.lua, toutes les recipes dans recipes.lua, etc… C'est plus facile de s'y retrouver.

La commande dofile(adrese_du_fichier) permet en suite d'intégrer le fichier séparé au fichier init.lua comme s'il en faisait partie : http://luatut.com/dofile.html.

Ici, tu pourrais l'utiliser comme ça (en début d'init.lua : 
`dofile(minetest.get_modpath("rythium").."/nodes.lua")`

Et pareil pour les autres fichiers lua.

**Comment by mega-gigaMynetest** [comment]
Mdr, oui en effet ce serait mieux.
Avec le commit que je viens de faire on passe de 60 lignes désorganisée a 350, donc bon faudra quand même penser à le faire mais pour l'instant je laisse l'issue ouverte.
À ne pas oublier

**Comment by mega-gigaMynetest** [comment]
C'est fait !
